qwen-2.5-7b-instruct:
    model_name: qwen/qwen-2.5-7b-instruct
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

qwen2.5-32b-instruct:
    model_name: qwen/qwen2.5-32b-instruct
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

qwen-2.5-72b-instruct:
    model_name: qwen/qwen-2.5-72b-instruct
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

gpt-4.5-preview: # TODO: so expensive
    model_name: openai/gpt-4.5-preview
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

gpt-4o-2024-11-20:
    model_name: openai/gpt-4o-2024-11-20
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

gpt-4o-mini:
    model_name: openai/gpt-4o-mini
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

gpt-4-1106-preview:
    model_name: openai/gpt-4-1106-preview
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

gemini-2.0-flash-lite-001:
    model_name: google/gemini-2.0-flash-lite-001
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

gemini-2.0-flash-001:
    model_name: google/gemini-2.0-flash-001
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64


gemini-2.0-pro-exp-02-05: # TODO
    model_name: google/gemini-2.0-pro-exp-02-05:free
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

claude-3.5-sonnet:
    model_name: anthropic/claude-3.5-sonnet
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

claude-3.5-sonnet-20240620:
    model_name: anthropic/claude-3.5-sonnet-20240620
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

claude-3.7-sonnet:
    model_name: anthropic/claude-3.7-sonnet
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

minimax-01:
    model_name: minimax/minimax-01
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

llama-3.1-8b-instruct:
    model_name: meta-llama/llama-3.1-8b-instruct
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

llama-3.1-70b-instruct:
    model_name: meta-llama/llama-3.1-70b-instruct
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

llama-3.3-70b-instruct:
    model_name: meta-llama/llama-3.3-70b-instruct
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

llama-3.1-405b-instruct:
    model_name: meta-llama/llama-3.1-405b-instruct
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

gemma-2-27b-it:
    model_name: google/gemma-2-27b-it
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

gemma-2-9b-it:
    model_name: google/gemma-2-9b-it
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

grok-2-1212:
    model_name: x-ai/grok-2-1212
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

mistral-small-24b-instruct-2501:
    model_name: mistralai/mistral-small-24b-instruct-2501
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

mistral-large-2411:
    model_name: mistralai/mistral-large-2411
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

hermes-3-llama-3.1-70b:
    model_name: nousresearch/hermes-3-llama-3.1-70b
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

hermes-3-llama-3.1-405b:
    model_name: nousresearch/hermes-3-llama-3.1-405b
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

deepseek-v3:
    model_name: deepseek/deepseek-chat
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

llama-3.1-nemotron-70b-instruct:
    model_name: nvidia/llama-3.1-nemotron-70b-instruct
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

command-r-08-2024:
    model_name: cohere/command-r-08-2024
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

command-r7b-12-2024:
    model_name: cohere/command-r7b-12-2024
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

command-r-plus-08-2024:
    model_name: cohere/command-r-plus-08-2024
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

lfm-3b:
    model_name: liquid/lfm-3b
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

lfm-7b:
    model_name: liquid/lfm-7b
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

lfm-40b:
    model_name: liquid/lfm-40b
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

nova-lite-v1:
    model_name: amazon/nova-lite-v1
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

nova-micro-v1:
    model_name: amazon/nova-micro-v1
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

nova-pro-v1:
    model_name: amazon/nova-pro-v1
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

claude-3.5-haiku:
    model_name: anthropic/claude-3.5-haiku
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

wizardlm-2-8x22b:
    model_name: microsoft/wizardlm-2-8x22b
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64
