qwen-2.5-7b-instruct:
    model_name: qwen/qwen-2.5-7b-instruct
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 128

qwen2.5-32b-instruct:
    model_name: qwen/qwen2.5-32b-instruct
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 32

qwen-2.5-72b-instruct:
    model_name: qwen/qwen-2.5-72b-instruct
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 128

gpt-4.5-preview:
    model_name: gpt-4.5-preview
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

gpt-4o-2024-11-20:
    model_name: gpt-4o-2024-11-20
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

gpt-4o-mini:
    model_name: gpt-4o-mini
    endpoints:
        - api_base: https://api.openai.com/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 128

gpt-4-1106-preview:
    model_name: gpt-4-1106-preview
    endpoints:
        - api_base: https://api.openai.com/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

gemini-2.0-flash-lite-001:
    model_name: google/gemini-2.0-flash-lite-001
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

gemini-2.0-flash-001:
    model_name: google/gemini-2.0-flash-001
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 128

gemini-2.0-pro-exp-02-05:
    model_name: gemini-2.0-pro-exp-02-05
    endpoints:
        - api_base: https://generativelanguage.googleapis.com/v1beta/openai/
          api_key: # Place your api_key
    api_type: openai
    parallel: 1

claude-3.5-sonnet:
    model_name: anthropic/claude-3.5-sonnet
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

claude-3.5-sonnet-20240620:
    model_name: anthropic/claude-3.5-sonnet-20240620
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

claude-3.7-sonnet:
    model_name: anthropic/claude-3.7-sonnet
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

minimax-01:
    model_name: minimax/minimax-01
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

llama-3.1-8b-instruct:
    model_name: meta-llama/llama-3.1-8b-instruct
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

llama-3.1-70b-instruct:
    model_name: meta-llama/llama-3.1-70b-instruct
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

llama-3.3-70b-instruct:
    model_name: meta-llama/llama-3.3-70b-instruct
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

llama-3.1-405b-instruct:
    model_name: meta-llama/llama-3.1-405b-instruct
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

gemma-2-27b-it:
    model_name: google/gemma-2-27b-it
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

gemma-2-9b-it:
    model_name: google/gemma-2-9b-it
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

grok-2-1212:
    model_name: x-ai/grok-2-1212
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

mistral-small-24b-instruct-2501:
    model_name: mistralai/mistral-small-24b-instruct-2501
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

mistral-large-2411:
    model_name: mistralai/mistral-large-2411
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

hermes-3-llama-3.1-70b:
    model_name: nousresearch/hermes-3-llama-3.1-70b
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

hermes-3-llama-3.1-405b:
    model_name: nousresearch/hermes-3-llama-3.1-405b
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

deepseek-v3:
    model_name: deepseek/deepseek-chat
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

llama-3.1-nemotron-70b-instruct:
    model_name: nvidia/llama-3.1-nemotron-70b-instruct
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

command-r-08-2024:
    model_name: cohere/command-r-08-2024
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

command-r7b-12-2024:
    model_name: cohere/command-r7b-12-2024
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

command-r-plus-08-2024:
    model_name: cohere/command-r-plus-08-2024
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

lfm-3b:
    model_name: liquid/lfm-3b
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

lfm-7b:
    model_name: liquid/lfm-7b
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

lfm-40b:
    model_name: liquid/lfm-40b
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

nova-lite-v1:
    model_name: amazon/nova-lite-v1
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 128

nova-micro-v1:
    model_name: amazon/nova-micro-v1
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 128

nova-pro-v1:
    model_name: amazon/nova-pro-v1
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 128

claude-3.5-haiku:
    model_name: anthropic/claude-3.5-haiku
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

wizardlm-2-8x22b:
    model_name: microsoft/wizardlm-2-8x22b
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 128

o3-mini-low:
    model_name: o3-mini
    endpoints:
        - api_base: https://api.openai.com/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

o3-mini-medium:
    model_name: o3-mini
    endpoints:
        - api_base: https://api.openai.com/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

o3-mini-high:
    model_name: o3-mini
    endpoints:
        - api_base: https://api.openai.com/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

o1-low:
    model_name: o1
    endpoints:
        - api_base: https://api.openai.com/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 32

o1-medium:
    model_name: o1
    endpoints:
        - api_base: https://api.openai.com/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 16

gemma-3-27b-it:
    model_name: google/gemma-3-27b-it
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 128

jamba-1.6-large:
    model_name: ai21/jamba-1.6-large
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 128

jamba-1.6-mini:
    model_name: ai21/jamba-1.6-mini
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

command-a:
    model_name: cohere/command-a
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

olmo-2-0325-32b-instruct:
    model_name: allenai/olmo-2-0325-32b-instruct
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 16

mistral-small-3.1-24b-instruct-2503:
    model_name: mistralai/mistral-small-3.1-24b-instruct-2503
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

o1-high:
    model_name: o1
    endpoints:
        - api_base: https://api.openai.com/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 32

deepseek-chat-v3-0324:
    model_name: deepseek/deepseek-chat-v3-0324
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 512

gemini-2.0-flash-thinking-exp-01-21:
    model_name: gemini-2.0-flash-thinking-exp-01-21
    endpoints:
        - api_base: https://generativelanguage.googleapis.com/v1beta/openai/
          api_key: # Place your api_key
    api_type: openai
    parallel: 5

gemini-2.5-pro-exp-03-25:
    model_name: gemini-2.5-pro-exp-03-25
    endpoints:
        - api_base: https://generativelanguage.googleapis.com/v1beta/openai/
          api_key: # Place your api_key
    api_type: openai
    parallel: 3

deepseek-r1:
    model_name: deepseek/deepseek-r1
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 32

chatgpt-4o-latest(2025-03-26):
    model_name: chatgpt-4o-latest
    endpoints:
        - api_base: https://api.openai.com/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

qwq-32b:
    model_name: qwen/qwq-32b
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

claude-3.7-sonnet(thinking):
    model_name: anthropic/claude-3.7-sonnet:thinking
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

qwen-turbo:
    model_name: qwen/qwen-turbo
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 32

qwen-plus:
    model_name: qwen/qwen-plus
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 32

qwen-max:
    model_name: qwen/qwen-max
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

quasar-alpha:
    model_name: openrouter/quasar-alpha
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 32

grok-3-beta:
    model_name: x-ai/grok-3-beta
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

grok-3-mini-beta:
    model_name: x-ai/grok-3-mini-beta
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

gpt-4.1-nano-2025-04-14:
    model_name: gpt-4.1-nano-2025-04-14
    endpoints:
        - api_base: https://api.openai.com/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

gpt-4.1-mini-2025-04-14:
    model_name: gpt-4.1-mini-2025-04-14
    endpoints:
        - api_base: https://api.openai.com/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

gpt-4.1-2025-04-14:
    model_name: gpt-4.1-2025-04-14
    endpoints:
        - api_base: https://api.openai.com/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

llama-4-scout:
    model_name: meta-llama/llama-4-scout
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

llama-4-maverick:
    model_name: meta-llama/llama-4-maverick
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

o4-mini-low:
    model_name: o4-mini
    endpoints:
        - api_base: https://api.openai.com/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

o4-mini-medium:
    model_name: o4-mini
    endpoints:
        - api_base: https://api.openai.com/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

o4-mini-high:
    model_name: o4-mini
    endpoints:
        - api_base: https://api.openai.com/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

o3-low:
    model_name: o3
    endpoints:
        - api_base: https://api.openai.com/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

o3-medium:
    model_name: o3
    endpoints:
        - api_base: https://api.openai.com/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

o3-high:
    model_name: o3
    endpoints:
        - api_base: https://api.openai.com/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

gemini-2.5-flash-preview:
    model_name: google/gemini-2.5-flash-preview
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64

gemini-2.5-flash-preview(thinking):
    model_name: google/gemini-2.5-flash-preview:thinking
    endpoints:
        - api_base: https://openrouter.ai/api/v1
          api_key: # Place your api_key
    api_type: openai
    parallel: 64