name: config of answer generation for ko-arena-hard-v0.1

bench_name: ko-arena-hard-v0.1

temperature: 0.0
max_tokens: 4096
num_choices: 1

# a list of model to generate answers
model_list:
  - gpt-4o-mini-2024-07-18
  - gpt-4o-2024-11-20
  - gpt-4o-2024-08-06
  - gemma-2-9b-it
  - claude-3-5-haiku-20241022
  - claude-3-5-sonnet-20241022